
const judges = [
    {"name":"Teresita Cerdeira","cluster":"A"},
    {"name":"Amelia Perales","cluster":"A"},
    {"name":"Juan Antonio Miguez","cluster":"A"},
    {"name":"Sonia Chibane","cluster":"A"},
    {"name":"Viktor Szabó","cluster":"A"},
    {"name":"Anna Csurgai","cluster":"A"},
    {"name":"György Szoták","cluster":"A"},
    {"name":"Adam Bell","cluster":"A"},
    {"name":"Susan Cummings","cluster":"A"},
    {"name":"Martin Henry","cluster":"A"},
    {"name":"Justin Rocyn-Jones","cluster":"A"},
    {"name":"Blake Kendrick","cluster":"A"},
    {"name":"Javier Merino","cluster":"B"},
    {"name":"Virginia Gomez","cluster":"B"},
    {"name":"Maureen Mcloughlin","cluster":"B"},
    {"name":"Adriana Mateu","cluster":"B"},
    {"name":"Szilárd Székely","cluster":"B"},
    {"name":"Levente Páger","cluster":"B"},
    {"name":"Andrew Ellingford","cluster":"B"},
    {"name":"Mary Jeffries","cluster":"B"},
    {"name":"Ellie Poltorak","cluster":"B"},
    {"name":"Tom Hoverd","cluster":"B"},
    {"name":"Harvey Alexander","cluster":"B"},
    {"name":"Cristina Costa","cluster":"B"},
    {"name":"Cristina Mendoza","cluster":"C"},
    {"name":"Diego Dedaceck","cluster":"C"},
    {"name":"Iria Mavji","cluster":"C"},
    {"name":"Hajnalka Battancs","cluster":"C"},
    {"name":"Róbert Bónay","cluster":"C"},
    {"name":"Dániel Jankovics","cluster":"C"},
    {"name":"Ashleigh Hall","cluster":"C"},
    {"name":"Emily Thompson","cluster":"C"},
    {"name":"Leah Symes","cluster":"C"},
    {"name":"James Smith","cluster":"C"},
    {"name":"Ian Williamson","cluster":"C"},
    {"name":"Leo Stott","cluster":"C"},
    {"name":"Wall Navarro","cluster":"D"},
    {"name":"Gary Hannigan","cluster":"D"},
    {"name":"Marina Dávila","cluster":"D"},
    {"name":"Emese Dudás","cluster":"D"},
    {"name":"Gyöngyi Csányi","cluster":"D"},
    {"name":"Anikó Mazány-Bencze","cluster":"D"},
    {"name":"Sabin Prunau","cluster":"D"},
    {"name":"Alison Dennigton","cluster":"D"},
    {"name":"Aidan Ferris","cluster":"D"},
    {"name":"Jake Rickhuss","cluster":"D"},
    {"name":"Michael Dyer","cluster":"D"},
    {"name":"Holly Garcia","cluster":"D"},
    {"name":"Nick Thomson","cluster":"E"},
    {"name":"Alexis Shirtliff","cluster":"E"},
    {"name":"Nigel Wilson","cluster":"E"},
    {"name":"Matteo","cluster":"E"},
    {"name":"Jose Antonio","cluster":"E"},
    {"name":"Victor Perez","cluster":"E"},
    {"name":"Hajnalka Battancs (final round)","cluster":"E"},
    {"name":"Róbert Bónay (final round)","cluster":"E"},
    {"name":"Peter Nochta","cluster":"E"},    
]

export default async function handler(req, res) {
    res.json(judges);
}